services:
  - type: web
    name: care-tracker-backend
    env: node
    buildCommand: cd backend && npm install && npm start
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PCO_CLIENT_ID
        sync: false
      - key: PCO_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: care-tracker-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://care-tracker-backend.onrender.com (or your backend's Render URL) 